---
mysql:
  host: localhost
  port: 3306
  user: root
  password: '123456'
  database: cmdb_go
  create_database_if_not_exist: false
redis:
  host: localhost
  port: 6379
  pool: 10
  password: ''
  database: 0
gin:
  mode: debug       // mode选项： release|debug
  listen: ":8130"