---
mysql:
  host: 10.1.16.151
  port: 3306
  user: dba
  password: '123456'
  database: cmdb
  create_database_if_not_exist: true
redis:
  host: localhost
  port: 6379
  pool: 10
  password: ''
  database: 0
gin:
  mode: debug       // mode选项： release|debug
  listen: ":8130"