---
mysql:
  host: localhost
  port: 3306
  user: root
  password: ''
  database: cmdb
  create_database_if_not_exist: true
redis:
  host: localhost
  port: 6379
  pool: 10
  password: ''
  database: 0
gin:
  mode: debug       // mode type： release or debug
  listen: ":8130"